### ISSUE TITLE
几个代码问题：encoder和label

### ISSUE THREAD

**Issue by laisimiao** [vision4robotics/HiFT#1]
1、请问一下，我感觉这里`self.gamma*weight*x `应该不用再乘以x吧？否则跟论文里面不太一样，就是**Cattention**模块，也就是论文中的modulation layer
https://github.com/vision4robotics/HiFT/blob/7f560e9ca1506f4b275f73e8c9ca4d34bec945ce/pysot/models/utile/tran.py#L32
2、这个标签生成方法是不是和SiamAPN用的是同一个？

**Comment by vision4robotics** [comment]
1. 非常感谢您的关注，我们的工作正在逐步更新中，我们仍在校对尚没有完全结束。
2. 生成方式并不相同。APN目的是生成自适应锚框，并不是最终结果而HiFT是Anchor-free的方法，因此导致了标签生成方式的不同，APN关注区域更大。
