### ISSUE TITLE
Could you please provide the result files of comparison trackers?

### ISSUE THREAD

**Issue by bit-bcilab** [vision4robotics/HiFT#11]
We notice that only the result files of your proposed tracker are uploaded on UAV123 and DTB70. 
We would greatly appreciate you if you can provide the result files of other comparison trackers in your paper, which will make us cite your work in our paper much more convenient.

**Comment by ziangcao0312** [comment]
For most cf trackers, you can find them at https://github.com/vision4robotics/DCFTracking4UAV. Others are DTB: https://drive.google.com/file/d/1nbqiT7NRXoghe2_v5pjqagpDXLmP7UMH/view?usp=sharing and https://pan.baidu.com/s/1-V4JbKvmVPm0aOKWTOQtyQ. UAV123: https://drive.google.com/file/d/1hCk9t6fbLJyM6TrtgCgfl-RON86lijQJ/view?usp=sharing

**Comment by ziangcao0312** [comment]
For most cf trackers, you can find them at https://github.com/vision4robotics/DCFTracking4UAV. Others are DTB: https://drive.google.com/file/d/1nbqiT7NRXoghe2_v5pjqagpDXLmP7UMH/view?usp=sharing and https://pan.baidu.com/s/1-V4JbKvmVPm0aOKWTOQtyQ. UAV123: https://drive.google.com/file/d/1hCk9t6fbLJyM6TrtgCgfl-RON86lijQJ/view?usp=sharing

**Comment by ziangcao0312** [comment]
For most cf trackers, you can find them at https://github.com/vision4robotics/DCFTracking4UAV. Others are DTB: https://drive.google.com/file/d/1nbqiT7NRXoghe2_v5pjqagpDXLmP7UMH/view?usp=sharing and https://pan.baidu.com/s/1-V4JbKvmVPm0aOKWTOQtyQ  (code:kh3e). UAV123: https://drive.google.com/file/d/1hCk9t6fbLJyM6TrtgCgfl-RON86lijQJ/view?usp=sharing
