### ISSUE TITLE
关于OT和FT

### ISSUE THREAD

**Issue by yangjiangeyjg** [vision4robotics/HiFT#3]
请问消融实验中OT和FT的transformer结构是什么样的啊，看了论文不太懂

**Comment by CcCc-ceil** [comment]
OT是attention is all your need 论文中的使用object query 结构。FT是仅将object query 替换成feature map后的结构。

**Comment by Jee-King** [comment]
你好，请问 HFT 相较于 FT 是不是多了modulation layer，并使用了多层feature maps
