### ISSUE TITLE
结果咨询

### ISSUE THREAD

**Issue by triumph693** [vision4robotics/HiFT#6]
请问一下，为什么我用您的代码在自己机器上跑出来的模型，然后在UAV123上测试，预测出来的结果为什么很不正常呢，后两个值都是10
<img width="257" alt="1634730578(1)" src="https://user-images.githubusercontent.com/83324302/138087170-99dd30a1-33da-4817-b59d-90058e39e84f.png">
<img width="257" alt="1634730578(1)" src="https://user-images.githubusercontent.com/83324302/138087453-075339f7-8090-45c7-b43a-405e696b2f9d.png">

**Comment by jackydinosaur** [comment]
@triumph693  Hello ,  I have the same problem.
Could you tell me what  training datasets did you  train？
I can't download  YOUTUBEBB data and pretrained model from BaiduYun.
Therefore , I train model with 'VID','COCO','DET', and got the same problem.
Another question, Did you test pretrained model: general_model on 'UAV123'？

**Comment by triumph693** [comment]
> @triumph693 Hello , I have the same problem. Could you tell me what training datasets did you train？ I can't download YOUTUBEBB data and pretrained model from BaiduYun. Therefore , I train model with 'VID','COCO','DET', and got the same problem. Another question, Did you test pretrained model: general_model on 'UAV123'？

我使用的数据集是GOT10k,因为我看其他数据集都很大，这个算小的，其他的没有下过，我在预训练模型上测试完了，结果还可以。

**Comment by whjzsy** [comment]
![QQ图片20211030170202](https://user-images.githubusercontent.com/28587699/139526987-ca260ae2-980f-4506-bf62-14de01ff54fc.png)
我遇到相同的问题，结果最后两位都是“10”，不知道哪里出问题了。

**Comment by triumph693** [comment]
> ![QQ图片20211030170202](https://user-images.githubusercontent.com/28587699/139526987-ca260ae2-980f-4506-bf62-14de01ff54fc.png) 我遇到相同的问题，结果最后两位都是“10”，不知道哪里出问题了。

你训练时用的数据集是哪几个呀，我只用了Got10k, 你有用 COCO , ImageNet VID , GOT-10K and Youtube-BB这几个数据集么

**Comment by jackydinosaur** [comment]
@triumph693 Hello, could you share me the **Got10k** dataset links , please?  Thanks!
I have requested the link for dataset multiple times, but I haven't received it yet.

**Comment by vision4robotics** [comment]
如果你们只用GOT进行训练，建议你们看一下第一个Epoch 的测试结果，如果第一个epoch还是这个问题，那就是刚上来训练就是没有效果，如果第一个epoch可以进行一部分跟踪，那就是之后由于70个epoch太多而产生过拟合。
我们在测试代码的时候并没有遇到这类问题，所以如果可以尽量和我们的四个train_dataset 保持一致。

**Comment by ghostbreaken** [comment]
> 我还没有解决，不过我咨询了作者，作者给了我回复，下面是作者的回复：
> 
> 首先，我们测试代码的时候从来没出现过这种情况，是不是你数据集数据准备出现了问题，建议你最好debug确定一下输入的数据是不是正确的。看一下自动保存的log文件里面的loss是否是下降。另外我们的batchsize是和num gpu 有关的，如果num gpu减少一倍，batchsize也要减少一倍这样才能保证一个gpu上分到的数据量和我们训练的保持一致。
> 
> 您能不能给我发一下DTB70数据集的下载链接，我没有找到这个数据集，期待您的回复。
老哥 你解决问题了嘛 我试着用6个数据集训练 后两位也是10

**Comment by ghostbreaken** [comment]
> ![QQ图片20211030170202](https://user-images.githubusercontent.com/28587699/139526987-ca260ae2-980f-4506-bf62-14de01ff54fc.png) 我遇到相同的问题，结果最后两位都是“10”，不知道哪里出问题了。

老哥，你的问题解决了嘛

**Comment by ghostbreaken** [comment]
> > ![QQ图片20211030170202](https://user-images.githubusercontent.com/28587699/139526987-ca260ae2-980f-4506-bf62-14de01ff54fc.png) 我遇到相同的问题，结果最后两位都是“10”，不知道哪里出问题了。
> 
> 你训练时用的数据集是哪几个呀，我只用了Got10k, 你有用 COCO , ImageNet VID , GOT-10K and Youtube-BB这几个数据集么

老哥 你的问题解决了嘛？我用了6个数据集训练，后两位也是10
